version: '3'

services:
  auth-generator:
    image: andrianovartemii/gm-test-task-auth-generator:latest
    ports:
      - "8080:8080"
    networks:
      - internal
    environment:
      AUTH_TOKEN_LIFETIME: 200

  pgsql:
    image: postgres:15
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

  migrations:
    image: migrations
    networks:
      - internal
    depends_on:
      - pgsql
    restart: "no"
    entrypoint: ["sh", "-c", "go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest && migrate -path ./migrations -database \"postgres://${DB_USER}:${DB_PASSWORD}@pgsql:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE}\" up"]

  getmark-home:
    image: getmark-home
    depends_on:
      - migrations
      - auth-generator
    ports:
      - "8081:8080"
    networks:
      - internal
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSL_MODE: ${DB_SSL_MODE}
      AUTH_SERVICE_URL: http://auth-generator:8080

networks:
  internal:
    driver: bridge